
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Apr 28 17:23:45 CEST 2016
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LT = 14;
  public static final int IDENT = 22;
  public static final int ELSE = 20;
  public static final int PLUS = 5;
  public static final int LP = 10;
  public static final int RP = 11;
  public static final int END = 3;
  public static final int EOS = 9;
  public static final int IF = 18;
  public static final int GT = 15;
  public static final int BEGIN = 2;
  public static final int NUMBER = 21;
  public static final int EOF = 0;
  public static final int MULT = 7;
  public static final int ELSEIF = 19;
  public static final int SET = 17;
  public static final int DIV = 8;
  public static final int MINUS = 6;
  public static final int PRINT = 4;
  public static final int error = 1;
  public static final int EQ = 16;
  public static final int KR = 12;
  public static final int KL = 13;
}

