
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 24 15:47:32 CEST 2017
//----------------------------------------------------

import java_cup.runtime.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Mon Apr 24 15:47:32 CEST 2017
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\021\000\002\002\005\000\002\002\004\000\002\005" +
    "\006\000\002\003\004\000\002\003\004\000\002\004\006" +
    "\000\002\006\006\000\002\007\004\000\002\007\003\000" +
    "\002\010\006\000\002\010\010\000\002\011\005\000\002" +
    "\011\005\000\002\011\005\000\002\012\004\000\002\012" +
    "\002\000\002\013\006" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\055\000\004\004\006\001\002\000\004\005\014\001" +
    "\002\000\004\002\012\001\002\000\004\013\007\001\002" +
    "\000\004\006\010\001\002\000\004\014\011\001\002\000" +
    "\004\005\uffff\001\002\000\004\002\000\001\002\000\006" +
    "\005\014\015\057\001\002\000\004\013\053\001\002\000" +
    "\004\005\014\001\002\000\006\007\017\012\020\001\002" +
    "\000\004\013\040\001\002\000\004\013\033\001\002\000" +
    "\010\007\017\012\020\015\023\001\002\000\010\007\ufff9" +
    "\012\ufff9\015\ufff9\001\002\000\010\005\ufff2\011\ufff2\015" +
    "\ufff2\001\002\000\010\007\ufffa\012\ufffa\015\ufffa\001\002" +
    "\000\010\005\ufffc\011\027\015\ufffc\001\002\000\010\005" +
    "\ufff3\011\ufff3\015\ufff3\001\002\000\004\013\030\001\002" +
    "\000\004\006\031\001\002\000\004\014\032\001\002\000" +
    "\010\005\ufff1\011\ufff1\015\ufff1\001\002\000\004\006\034" +
    "\001\002\000\004\014\035\001\002\000\006\007\017\012" +
    "\020\001\002\000\010\007\017\012\020\015\037\001\002" +
    "\000\010\007\ufff7\012\ufff7\015\ufff7\001\002\000\006\006" +
    "\041\010\042\001\002\000\004\016\050\001\002\000\004" +
    "\016\045\001\002\000\004\014\044\001\002\000\010\007" +
    "\ufff8\012\ufff8\015\ufff8\001\002\000\006\006\046\010\047" +
    "\001\002\000\004\014\ufff6\001\002\000\004\014\ufff4\001" +
    "\002\000\004\010\051\001\002\000\004\014\ufff5\001\002" +
    "\000\006\005\ufffd\015\ufffd\001\002\000\004\006\054\001" +
    "\002\000\004\014\055\001\002\000\006\007\ufffb\012\ufffb" +
    "\001\002\000\006\005\ufffe\015\ufffe\001\002\000\004\002" +
    "\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\055\000\006\002\004\005\003\001\001\000\010\003" +
    "\012\004\014\006\015\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\004\055\006\015\001\001" +
    "\000\002\001\001\000\006\004\051\006\015\001\001\000" +
    "\006\007\020\010\021\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\010\023\001\001\000\002\001\001\000" +
    "\004\012\024\001\001\000\002\001\001\000\004\013\025" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\007\035\010\021\001\001\000" +
    "\004\010\023\001\001\000\002\001\001\000\004\011\042" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



        public static void main(String args[]) throws Exception {
                new parser(new Yylex(System.in)).parse();        } // End Main

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // commercial ::= AD LP ITEM RP 
            {
              Object RESULT =null;
		 System.out.println("    PARSER:: commercial <== AD LP ITEM RP");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("commercial",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // publicity ::= 
            {
              Object RESULT =null;
		 /* lambda */ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("publicity",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // publicity ::= publicity commercial 
            {
              Object RESULT =null;
		 System.out.println("    PARSER:: publicity <== publicity commercial");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("publicity",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // parameters ::= ACTOR COMMA ACTOR 
            {
              Object RESULT =null;
		 System.out.println("    PARSER:: parameters <== ACTOR COMMA ACTOR");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("parameters",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // parameters ::= ITEM COMMA ACTOR 
            {
              Object RESULT =null;
		 System.out.println("    PARSER:: parameters <== ITEM COMMA ACTOR");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("parameters",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // parameters ::= ACTOR COMMA ITEM 
            {
              Object RESULT =null;
		 System.out.println("    PARSER:: parameters <== ACTOR COMMA ITEM");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("parameters",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // unaction ::= FOR LP ITEM RP actions END 
            {
              Object RESULT =null;
		 System.out.println("    PARSER::actions <== FOR LP ITEM RP actions END");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("unaction",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // unaction ::= ACTION LP parameters RP 
            {
              Object RESULT =null;
		 System.out.println("    PARSER:: action <== ACTION LP parameters RP");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("unaction",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // actions ::= unaction 
            {
              Object RESULT =null;
		 System.out.println("    PARSER:: actions <== unaction");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("actions",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // actions ::= actions unaction 
            {
              Object RESULT =null;
		 System.out.println("    PARSER:: actions <== actions unaction");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("actions",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // title_sketch ::= SKETCH LP ITEM RP 
            {
              Object RESULT =null;
		 System.out.println("    PARSER:: title_sketch <== SKETCK LP ITEM RP");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("title_sketch",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // sketch ::= title_sketch actions END publicity 
            {
              Object RESULT =null;
		 System.out.println("    PARSER:: sketch <== title_sketch actions END publicity");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sketch",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // sketchs ::= sketch sketch 
            {
              Object RESULT =null;
		 System.out.println("    PARSER:: sketchs <== sketch sketch");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sketchs",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // sketchs ::= sketchs sketch 
            {
              Object RESULT =null;
		 System.out.println("    PARSER:: sketchs <== sketchs sketch");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sketchs",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // title_chapter ::= CHAPTER LP ITEM RP 
            {
              Object RESULT =null;
		 System.out.println("    PARSER:: title_chapter <== CHAPTER LP ITEM RP");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("title_chapter",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= chapter EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // chapter ::= title_chapter sketchs END 
            {
              Object RESULT =null;
		 System.out.println("    PARSER:: chapter <== title_chapter sketchs END"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("chapter",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

