
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 24 15:47:32 CEST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ACTION = 5;
  public static final int LP = 9;
  public static final int ACTOR = 6;
  public static final int FOR = 8;
  public static final int AD = 7;
  public static final int EOF = 0;
  public static final int CHAPTER = 2;
  public static final int COMMA = 12;
  public static final int error = 1;
  public static final int SKETCH = 3;
  public static final int ITEM = 4;
  public static final int END = 11;
  public static final int RP = 10;
}

