
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jun 28 10:54:16 CEST 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 12;
  public static final int LP = 6;
  public static final int TRUE = 8;
  public static final int EOF = 0;
  public static final int FALSE = 9;
  public static final int error = 1;
  public static final int PRINT = 4;
  public static final int NOT = 10;
  public static final int COMMENT = 13;
  public static final int END = 3;
  public static final int EOS = 5;
  public static final int BEGIN = 2;
  public static final int OR = 11;
  public static final int RP = 7;
}

