
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 23 20:27:45 CEST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ACTION = 9;
  public static final int ACTOR = 11;
  public static final int LP = 7;
  public static final int AD = 5;
  public static final int EOF = 0;
  public static final int CHAPTER = 2;
  public static final int error = 1;
  public static final int COMMA = 6;
  public static final int SKETCH = 3;
  public static final int ITEM = 10;
  public static final int END = 4;
  public static final int RP = 8;
}

