
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 23 17:59:17 CEST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LT = 13;
  public static final int IDENT = 17;
  public static final int PLUS = 5;
  public static final int LP = 10;
  public static final int RP = 11;
  public static final int END = 3;
  public static final int EOS = 9;
  public static final int GT = 12;
  public static final int BEGIN = 2;
  public static final int EOF = 0;
  public static final int MULT = 6;
  public static final int NUMBER = 15;
  public static final int SET = 16;
  public static final int DIV = 8;
  public static final int MINUS = 7;
  public static final int PRINT = 4;
  public static final int error = 1;
  public static final int EQ = 14;
}

